### PR TITLE
Add fix for wkhtmltopdf on 18.04

### PR DESCRIPTION
**Pull request by boatrite**

### CODE REVIEW

**Comment by petitJAM** [comment]
Does this fix actually belong in subspace? Or is it something that should go in MD?

**Comment by boatrite** [comment]
That is a good question

**Comment by boatrite** [comment]
I was thinking about it and yeah, this might make more sense to just live in the doorman repo for now. Idk if this is a generally globally useful thing or not.

**Comment by petitJAM** [comment]
Yea this one seems very specific to Doorman.  Doing it there also means we aren't blocked on releasing a new version of this gem.

**Pull request closed without merging**
